### PR TITLE
fixed package.json

### PR DESCRIPTION
**Pull request by beetz12**
There were extra characters in package.json which I removed.

### CODE REVIEW

**Comment by shudsonbstar4** [comment]
@beetz12  Hey, thanks for catching this! I had been trying to run gulp and my cursor was in the wrong window, didn't notice, haha. I caught the issue earlier today, however, so I'm closing this PR. :)

**Comment by beetz12** [comment]
@shudsonbstar4 Haha no worries, it happens to the best of us. Sarah told me that you built the site from scratch in just a few hours. That's very impressive. What tools did you use?

**Comment by shudsonbstar4** [comment]
@beetz12 ahaha for sure. Well, I have some setup files (i.e., package.json, bower.json, and gulpfile.js) that I built out for other projects, and I just copied those over as boilerplate. I'm planning to go back and clean up the build process, make it better, etc, for this project. I'm not using anything other than what you see in those files. Mainly I wanted to learn more about building things without crutches.

**Comment by beetz12** [comment]
Yes building from scratch is the best way to learn. I don't know gulp that well but it definitely makes building projects easier. Have you ever used travis CI? It's a continuous integration framework. After you push your code to github, it will automatically run your tests, and if the tests pass, it will deploy your code to your web server.

**Pull request closed without merging**
